name:                refocus
version:             0.1.0.0
github:              "carymrobbins/refocus"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2018 Cary Robbins"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/carymrobbins/refocus#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- directory
- extra
- optparse-applicative
- process
- yaml

executables:
  refocus:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
